### ISSUE TITLE
ZW080 volume level broken in #2132

### ISSUE THREAD

**Issue by NobleKangaroo** [AlCalzone/node-zwave-js#4287]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

**What causes the bug?**

Pull #2132 (specifically blhoward2's commit [#d0d707f](https://github.com/blhoward2/node-zwave-js/commit/d0d707f1dec712797404d78a81f818842b0618de)) modified many Aeotec devices, in an attempt to standardize code that operates the devices. In the case of the ZW080-A17, the above-mentioned commit introduced erroneous behavior by modifying the 0xff bitmask code, linking it to the ["wattage_percent_trigger" template](https://github.com/zwave-js/node-zwave-js/blob/95a59bdadfc4f9a0e8e4af311e61caddc8744283/packages/config/config/devices/0x0086/templates/aeotec_template.json#L1572-L1577). This template is not appropriate here, as the [official documentation](http://manuals-backend.z-wave.info/make.php?lang=en&sku=ZW080-A17&cert=ZC10-14090012) for this device states that parameter 37 should be used for both the siren sound (bitmask 0xff00) and siren volume (bitmask 0xff), not a "wattage percent sensor".
&nbsp;

**What needs to be done to fix the bug?**

[zw080.json](https://github.com/zwave-js/node-zwave-js/tree/master/packages/config/config/devices/0x0086/zw080.json) needs to be adjusted to re-implement volume selection. The original code is below for reference.
```json
		"37[0xff]": {
			"label": "Siren Volume",
			"valueSize": 2,
			"minValue": 0,
			"maxValue": 3,
			"defaultValue": 3,
			"readOnly": false,
			"writeOnly": false,
			"allowManualEntry": true,
			"options": [
				{
					"label": "Do not change the current volume",
					"value": 0
				},
				{
					"label": "Set the volume to 88 dB",
					"value": 1
				},
				{
					"label": "Set the volume to 100 dB",
					"value": 2
				},
				{
					"label": "Set the volume to 105 dB",
					"value": 3
				}
			]
		},
```

### Device information

n/a

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

Addon version: 0.1.54
Driver version: 8.11.6
Server version: 1.15.0

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

Worked before this update. Haven't noticed it hasn't been working as I haven't had an event that triggered an automation to try and update this device's configuration.

### Attach Driver Logfile

n/a

**Comment by NobleKangaroo** [comment]
Here's a Home Assistant service call, testing the operation of parameter 37. I can confirm that the tests are successful in doing what they should be doing. Hashes `#` can be moved around as needed and values changed, of course, to test this.
```
service: zwave_js.set_config_parameter
data:
  entity_id: switch.laundry_room_siren_siren

  # Sound - values: 1, 2, 3, 4, 5
  #parameter: "Siren Sound"
  #parameter: 37
  #bitmask: 0xff00
  #value: 3

  # Volume - values: 1 (88 dB), 2 (100 dB), 3 (105 dB)
  # Followed the parameter name from DSD31 - https://devices.zwave-js.io/?jumpTo=0x0086:0x0004:0x0050:0.0
  # Referencing by name doesn't work; template is named "Minimum Power Percentage Change to Trigger Event"
  #parameter: "Volume"
  parameter: 37
  bitmask: 0xff
  value: 1
```

Should be fixed, and documentation updated to reflect the parameter name "Volume".
