### ISSUE TITLE
Aeotec - Multisensor 6 - ZW100 missing a value for config parameter 81

### ISSUE THREAD

**Issue by electrofloat** [AlCalzone/node-zwave-js#4360]
What causes the bug?
ZW100 (Firmware: 1.11) has only 2 values for config parameter 81 in zwavejs: Enable/Disable.
Openzwave correctly contains 3 values for this config parameter:
https://github.com/OpenZWave/open-zwave/blob/master/config/aeotec/zw100.xml#L316

If I set it with
```
service: zwave_js.set_value
data:
  command_class: '112'
  endpoint: '0'
  property: '81'
  value: 2
target:
  device_id: dev_id
```
to 2, I can completely disable the led blinking, which I was expecting it to do with the Disable config.

What do you observe?
I cannot turn off the blinking led completely.

What did you expect to happen?
To be able to turn off the blinking led completely.
