### ISSUE TITLE
Missing device configuration: Enbrighten (Jasco) Smart Fan Control 700 ( 58446 / ZWA4013 )

### ISSUE THREAD

**Issue by Nick2253** [AlCalzone/node-zwave-js#7671]
### Checklist

- [x] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [x] It was not [merged recently](https://github.com/zwave-js/zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/zwave-js/pulls?q=is%3Aopen+is%3Apr)

- [x] The device was interviewed completely and has no missing or `undefined` IDs

### Which device is missing?

Enbrighten (Jasco) Smart Fan Control 700 ( 58446 / ZWA4013 )

### Manufacturer ID

0x0063

### Product Type

0x4944

### Product ID

0x3533

### Firmware Version

1.26.1

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/4931

### Do you have a manual?

https://products.z-wavealliance.org/ProductManual/File?folder=&filename=cert_portal/certs/584/58446Fancontrolusermanual_1_1_1.pdf

**Comment by AlCalzone** [comment]
@zwave-js-bot import config 4931 from zwa

**Comment by kramttocs** [comment]
Thanks for getting this added. Since it's currently showing as a Light in HA, what's the correct way to get it to show as a fan? I've reinterviewed but no change.

**Comment by kramttocs** [comment]
I excluded, reset, and included but no change in how it's identified (still a multi level light)

**Comment by AlCalzone** [comment]
Z-Wave has no concept of a fan for some reason, so HA will need device specific discovery to discover this as a fan instead.

**Comment by Nick2253** [comment]
@AlCalzone that's not entirely correct.  Z-Wave does have a concept of a fan (device type `Fan Switch`), but such a device must be a 3-speed device.  If you want to make a device with more levels, like this device, then the only option is device type `Multilevel Switch DT`, which is basically a dimmer light switch.  This is really a problem that could be easily fixed by Z-Wave, but they haven't, so we're stuck here.

As examples, you can see that [Jasco 55259](https://products.z-wavealliance.org/products/3979?selectedFrequencyId=2) is type `Fan Switch`, but this product [Jasco 58446](https://products.z-wavealliance.org/products/4931?selectedFrequencyId=2) is type `Multilevel Switch DT`

@kramttocs To get it to show up as a fan in Home Assistant, you want to use the [Template Fan](https://www.home-assistant.io/integrations/template/#fan) in your configuration.  For example, this is how I set up my bedroom fan:

```
fan:
  - platform: template
    fans:
      master_bedroom_fan:
        unique_id: 'dcba487d-05fc-490a-9a92-0be4d00937bf'
        friendly_name: "Master Bedroom Fan"
        value_template: "{{ states('light.master_bedroom_fan') }}"
        percentage_template: "{{ ((state_attr('light.master_bedroom_fan', 'brightness') | float(0.0)) * 100/255) | round(0) |int }}"
        turn_on:
          service: light.turn_on
          entity_id: light.master_bedroom_fan
        turn_off:
          service: light.turn_off
          entity_id: light.master_bedroom_fan
        speed_count: 4
        set_percentage:
          service: light.turn_on
          entity_id: light.master_bedroom_fan
          data_template:
            brightness_pct: "{{ percentage | int }}"
```
